upstream fastcgi_backend {
    server unix:/run/php/php8.3-fpm.sock;
}

server {
    listen 80;
    server_name example.com;
    set $MAGE_ROOT /var/www/html/magento2;
    set $MAGE_MODE production;

    include /var/www/html/magento2/nginx.conf.sample;
}